name: Pantry's Unit Tests
on: [push, pull_request]

jobs:
  unit-tests-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit