name: Pantry's Unit Tests
on: [push, pull_request]

jobs:
  unit-tests-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test